name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - v*
env:
  CARGO_TERM_COLOR: always
jobs:
  publish:
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            protoc_suffix: linux-x86_64
    steps:
      - uses: actions/checkout@v4
      - run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v26.0/protoc-26.0-${{ matrix.job.protoc_suffix }}.zip
          unzip protoc-26.0-${{ matrix.job.protoc_suffix }}.zip
          sudo mv bin/protoc /usr/local/bin/
      - name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  release:
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            protoc_suffix: linux-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            protoc_suffix: osx-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            protoc_suffix: osx-aarch_64
    steps:
      - uses: actions/checkout@v4
      - run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v26.0/protoc-26.0-${{ matrix.job.protoc_suffix }}.zip
          unzip protoc-26.0-${{ matrix.job.protoc_suffix }}.zip
          sudo mv bin/protoc /usr/local/bin/
      - name: Build
        run: |
          cargo build --release
          mv target/release/stablessh stablessh-${{ matrix.job.target }}
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: stablessh-${{ matrix.job.target }}
